USE [Examen]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_INS_FUTBOLISTA]
   @PV_CEDULA VARCHAR (50),
   @PV_NOMBRES VARCHAR (50),
   @PV_APELLIDOS VARCHAR (50),
   @PD_FECHA_NACIMIENTO DATETIME,
   @PV_PAIS VARCHAR (50),
   @PV_DIRECCION VARCHAR(50),
   @PV_DESCRIPCION VARCHAR(50)

AS
	DECLARE @CONTADOR_ID INTEGER;
BEGIN
   



	SELECT @CONTADOR_ID=(CEDULA)
	FROM FUTBOLISTA;

	INSERT INTO FUTBOLISTA(CEDULA,NOMBRES,APELLIDOS,FECHA_NACIMIENTO,PAIS,DIRECCION,DESCRIPCION)
	VALUES(@PV_CEDULA,@PV_NOMBRES,@PV_APELLIDOS,@PV_FECHA_NACIMIENTO,@PV_PAIS,@PV_DIRECCION,@PV_DESCRIPCION);


END