USE [Examen]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_UPD_FUTBOLISTA]
   @PV_CEDULA VARCHAR (50),
   @PV_NOMBRES VARCHAR (50),
   @PV_APELLIDOS VARCHAR (50),
   @PV_FECHA_NACIMIENTO DATETIME,
   @PV_PAIS VARCHAR (50),
   @PV_DIRECCION VARCHAR(50),
   @PV_DESCRIPCION VARCHAR(50)


AS
	
BEGIN
   UPDATE FUTBOLISTA
   SET NOMBRES=@PV_NOMBRES,
   APELLIDOS=@PV_APELLIDOS,
   FECHA_NACIMIENTO=@PV_FECHA_NACIMIENTO,
   PAIS=@PV_PAIS,
   DIRECCION=@PV_DIRECCION,
   DESCRIPCION=@PV_DESCRIPCION
WHERE
  CEDULA=@PV_CEDULA


END